FROM ubuntu:focal
WORKDIR /app
COPY ./notebook/. .
# RUN pip install plotly sympy ipython
RUN apt-get update
RUN apt-get -y install python3 python3-pip
RUN pip3 install jupyterlab numpy scipy matplotlib plotly sympy ipympl
CMD ['jupyter', 'lab']
